include: 'https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml'

variables:
    BUNDLE: "scarlatti-dev.flatpak"
    GIT_SUBMODULE_STRATEGY: recursive

flatpak:
    variables:
        MANIFEST_PATH: "org.scarlatti.Scarlatti.json"
        FLATPAK_MODULE: "scarlatti"
        RUNTIME_REPO: 'https://nightly.gnome.org/gnome-nightly.flatpakrepo'
        APP_ID: "org.scarlatti.Scarlatti.Devel"
    extends: .flatpak
